import baca

distances = (6,)
y_offset_1 = 12
y_offset_2 = 40
y_offset_3 = 68
y_offset_4 = 96
y_offset_5 = 124
y_offset_6 = 152
y_offset_7 = 180
y_offset_8 = 208

breaks = baca.breaks(
    baca.page(
        baca.system(
            distances,
            measure=1,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=7,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=13,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=19,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=25,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=31,
            y_offset=y_offset_8,
        ),
        number=1,
    ),
    baca.page(
        baca.system(
            distances,
            measure=37,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=43,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=49,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=55,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=61,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=67,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=73,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=79,
            y_offset=y_offset_8,
        ),
        number=2,
    ),
    baca.page(
        baca.system(
            distances,
            measure=85,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=89,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=93,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=97,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=101,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=105,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=109,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=113,
            y_offset=y_offset_8,
        ),
        number=3,
    ),
    baca.page(
        baca.system(
            distances,
            measure=117,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=121,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=125,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=129,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=133,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=137,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=141,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=145,
            y_offset=y_offset_8,
        ),
        number=4,
    ),
    baca.page(
        baca.system(
            distances,
            measure=149,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=153,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=157,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=161,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=164,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=169,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=173,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=177,
            y_offset=y_offset_8,
        ),
        number=5,
    ),
    baca.page(
        baca.system(
            distances,
            measure=181,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=185,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=189,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=193,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=197,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=201,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=204,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=210,
            y_offset=y_offset_8,
        ),
        number=6,
    ),
    baca.page(
        baca.system(
            distances,
            measure=213,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=217,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=219,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=221,
            y_offset=y_offset_4,
        ),
        baca.system(
            # distances,
            (8,),
            measure=223,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=225,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=228,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=231,
            y_offset=y_offset_8,
        ),
        number=7,
    ),
    baca.page(
        baca.system(
            distances,
            measure=234,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=238,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=242,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=246,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=250,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=254,
            y_offset=y_offset_6 + 2,
        ),
        baca.system(
            distances,
            measure=258,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=262,
            y_offset=y_offset_8,
        ),
        number=8,
    ),
    baca.page(
        baca.system(
            distances,
            measure=266,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=270,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=274,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=277,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=281,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=284,
            y_offset=y_offset_6,
        ),
        number=9,
    ),
)

spacing = baca.scorewide_spacing(
    __file__,
    breaks=breaks,
    fallback_duration=(1, 16),
)
spacing.override((70, 72), (1, 4))
spacing.override([198, 200], (1, 2))
spacing.override([201, 203], (1, 2))
spacing.override(202, (1, 40)),
spacing.override([205, 209], (1, 4))
spacing.override((274, 286), (1, 4))

if __name__ == "__main__":
    baca.build.make_layout_ly(__file__)
