import baca

distances = (6,)
y_offset_1 = 12
y_offset_2 = 40
y_offset_3 = 68
y_offset_4 = 96
y_offset_5 = 124
y_offset_6 = 152
y_offset_7 = 180
y_offset_8 = 208

breaks = baca.breaks(
    baca.page(
        baca.system(
            distances,
            measure=1,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=7,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=13,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=19,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=25,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=32,
            y_offset=y_offset_8,
        ),
        number=1,
    ),
    baca.page(
        baca.system(
            distances,
            measure=35,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=45,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=49,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=53,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=61,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=65,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=70,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=79,
            y_offset=y_offset_8,
        ),
        number=2,
    ),
    baca.page(
        baca.system(
            distances,
            measure=85,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=87,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=89,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=91,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=93,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=95,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=97,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=99,
            y_offset=y_offset_8,
        ),
        number=3,
    ),
    baca.page(
        baca.system(
            distances,
            measure=101,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=103,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=105,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=107,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=109,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=111,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=113,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=115,
            y_offset=y_offset_8,
        ),
        number=4,
    ),
    baca.page(
        baca.system(
            distances,
            measure=117,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=119,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=122,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=125,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=129,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=132,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=135,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=137,
            y_offset=y_offset_8,
        ),
        number=5,
    ),
    baca.page(
        baca.system(
            distances,
            measure=141,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=143,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=145,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=147,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=149,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=151,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=153,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=155,
            y_offset=y_offset_8,
        ),
        number=6,
    ),
    baca.page(
        baca.system(
            distances,
            measure=157,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=161,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=165,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=169,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=173,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=177,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=181,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=185,
            y_offset=y_offset_8,
        ),
        number=7,
    ),
    baca.page(
        baca.system(
            distances,
            measure=189,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=193,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=197,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=201,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=205,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=209,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=213,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=218,
            y_offset=y_offset_8,
        ),
        number=8,
    ),
    baca.page(
        baca.system(
            distances,
            measure=222,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=224,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=229,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=233,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=237,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=241,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=245,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=249,
            y_offset=y_offset_8,
        ),
        number=9,
    ),
    baca.page(
        baca.system(
            distances,
            measure=253,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=257,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=261,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=265,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=269,
            y_offset=y_offset_5,
        ),
        baca.system(
            distances,
            measure=273,
            y_offset=y_offset_6,
        ),
        baca.system(
            distances,
            measure=277,
            y_offset=y_offset_7,
        ),
        baca.system(
            distances,
            measure=281,
            y_offset=y_offset_8,
        ),
        number=10,
    ),
)

spacing = baca.scorewide_spacing(
    __file__,
    breaks=breaks,
    fallback_duration=(1, 16),
)
spacing.override((25, 30), (1, 8))
spacing.override((18, 19), (1, 40))
spacing.override((31, 34), (1, 40))
spacing.override((45, 46), (1, 40))
spacing.override(48, (1, 40))
spacing.override(49, (1, 40))
spacing.override([61, 63], (1, 40))
spacing.override(222, (1, 8))

if __name__ == "__main__":
    baca.build.make_layout_ly(__file__)
