import baca

distances = (6, 16)
y_offset_1 = 12
y_offset_2 = 56
y_offset_3 = 100
y_offset_4 = 144
y_offset_5 = 188
y_offset_6 = 232

breaks = baca.breaks(
    baca.page(
        baca.system(
            distances,
            measure=1,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=5,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=11,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=16,
            y_offset=y_offset_5,
        ),
        number=1,
    ),
    baca.page(
        baca.system(
            distances,
            measure=21,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=26,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=31,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=36,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=41,
            y_offset=y_offset_5,
        ),
        number=2,
    ),
    baca.page(
        baca.system(
            distances,
            measure=46,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=51,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=56,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=61,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=66,
            y_offset=y_offset_5,
        ),
        number=3,
    ),
    baca.page(
        baca.system(
            distances,
            measure=71,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=76,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=81,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=86,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=91,
            y_offset=y_offset_5,
        ),
        number=4,
    ),
    baca.page(
        baca.system(
            distances,
            measure=96,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=101,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=106,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=111,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=116,
            y_offset=y_offset_5,
        ),
        number=5,
    ),
    baca.page(
        baca.system(
            distances,
            measure=121,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=126,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=131,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=136,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=141,
            y_offset=y_offset_5,
        ),
        number=6,
    ),
    baca.page(
        baca.system(
            distances,
            measure=146,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=151,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=156,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=161,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=166,
            y_offset=y_offset_5,
        ),
        number=7,
    ),
    baca.page(
        baca.system(
            distances,
            measure=171,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=176,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=181,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=186,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=191,
            y_offset=y_offset_5,
        ),
        number=8,
    ),
    baca.page(
        baca.system(
            distances,
            measure=196,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=201,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=206,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=211,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=216,
            y_offset=y_offset_5,
        ),
        number=9,
    ),
    baca.page(
        baca.system(
            distances,
            measure=221,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=226,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=231,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=236,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=241,
            y_offset=y_offset_5,
        ),
        number=10,
    ),
    baca.page(
        baca.system(
            distances,
            measure=246,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=251,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=256,
            y_offset=y_offset_3,
        ),
        baca.system(
            distances,
            measure=261,
            y_offset=y_offset_4,
        ),
        baca.system(
            distances,
            measure=265,
            y_offset=y_offset_5,
        ),
        number=11,
    ),
    baca.page(
        baca.system(
            distances,
            measure=271,
            y_offset=y_offset_1,
        ),
        baca.system(
            distances,
            measure=276,
            y_offset=y_offset_2,
        ),
        baca.system(
            distances,
            measure=281,
            y_offset=y_offset_3,
        ),
        number=12,
    ),
)

spacing = baca.scorewide_spacing(
    __file__,
    breaks=breaks,
    fallback_duration=(1, 16),
)

if __name__ == "__main__":
    baca.build.make_layout_ly(__file__)
