import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Skips',
                'Music_Context',
                'Wind_Section_Staff_Group',
                'Flute_Music_Staff',
                'Global_Rests',
                'Flute_Music_Voice',
                'Flute_Rest_Voice',
                'English_Horn_Music_Staff',
                'English_Horn_Music_Voice',
                'English_Horn_Rest_Voice',
                'Clarinet_Music_Staff',
                'Clarinet_Music_Voice',
                'Clarinet_Rest_Voice',
                'Percussion_Section_Staff_Group',
                'Piano_Staff_Group',
                'Piano_RH_Music_Staff',
                'Piano_RH_Music_Voice',
                'Piano_RH_Rest_Voice',
                'Piano_LH_Music_Staff',
                'Piano_LH_Music_Voice',
                'Piano_LH_Rest_Voice',
                'Piano_LH_Attack_Voice',
                'Piano_LH_Attack_Rest_Voice',
                'Percussion_Music_Staff',
                'Percussion_Music_Voice',
                'Percussion_Rest_Voice',
                'String_Section_Staff_Group',
                'Violin_Music_Staff',
                'Violin_Music_Voice',
                'Violin_Rest_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [279],
            ),
        ('duration', "0'23''"),
        ('final_measure_number', 286),
        ('first_measure_number', 279),
        ('phantom', True),
        ('segment_name', 'O'),
        ('segment_number', 16),
        ('start_clock_time', "12'00''"),
        ('stop_clock_time', "12'23''"),
        (
            'time_signatures',
            [
                '8/4',
                '7/4',
                '8/4',
                '7/4',
                '8/4',
                '7/4',
                '8/4',
                '7/4',
                ],
            ),
        ]
    )
